name: Update the AUR package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Get the latest release"
        id: latest_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Fetch the AppImage for x86_64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "CheatBreakerNet/Launcher"
          version: "tags/${{ steps.latest_release.outputs.tag_name }}"
          file: "CheatBreaker.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch the AppImage for arm64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "CheatBreakerNet/Launcher"
          version: "tags/${{ steps.latest_release.outputs.tag_name }}"
          file: "CheatBreaker-ARM64.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update the PKG version and md5sums in the PKGBUILD
        run: |
          sed -i 's/^pkgver=.*/pkgver=${{ steps.latest_release.outputs.tag_name }}/' ./AUR/PKGBUILD
          sed -i "s#^md5sums_x86_64=.*#md5sums_x86_64=('$(md5sum ./CheatBreaker.AppImage | cut -d' ' -f1)')#" ./AUR/PKGBUILD
          sed -i "s#^md5sums_arm64=.*#md5sums_arm64=('$(md5sum ./CheatBreaker-ARM64.AppImage | cut -d' ' -f1)')#" ./AUR/PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.2
        with:
          pkgname: cheatbreaker
          pkgbuild: ./AUR/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}