name: Update the AUR package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Get the latest release"
        id: latest_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Update the PKG version in the PKGBUILD
        run: |
          sed -i 's/^pkgver=.*/pkgver=${{ steps.latest_release.outputs.tag_name }}/' ./AUR/PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: offline-cheatbreaker
          pkgbuild: ./AUR/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
