on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get previous release tag
        id: previous-release
        uses: WyriHaximus/github-action-get-previous-tag@v1
      
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.previous-release.outputs.tag }}
          assets: CheatBreaker*