on:
  release:
    types: [published]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get previous release tag
        id: previous-release
        run: echo "tag=$(git tag --sort "-committerdate" | cut -d$'\n' -f2)" >> $GITHUB_OUTPUT
      
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.previous-release.outputs.tag }}
          assets: CheatBreaker*