on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "14303827"
          content: "||<@&1080980861320708096>||"
          footer_title: "Launcher Update"
          footer_icon_url: "https://cheatbreaker.net/v/images/logo-108.png"
          footer_timestamp: true
